### ISSUE TITLE
Search box magnifying glass click?

### ISSUE THREAD

**Issue by GeoffE1e6** [SharePoint/sp-dev-fx-webparts#696] opened 2018-11-22 19:32 UTC
Hi there Folks,

Am new to the search refiner and just working through placing it on a test site. The magnifying glass on the right of the search box - can this be set to be clickable so that users do not have to press return to carry out a search? That would make it closer to the classic experience :)

Cheers

G

**Comment by FranckyC** [comment] 2018-11-22 20:03
@GeoffE1e6 Good suggestion! Maybe a search button could be added to the search box also.

**Comment by FranckyC** [comment] 2018-11-28 23:37
Here you go @GeoffE1e6 https://github.com/SharePoint/sp-dev-fx-webparts/pull/695

**Comment by GeoffE1e6** [comment] 2018-11-29 13:32
Hi,
Thanks! Er - is it available for download / test? Silly question if you're still updating... Just re-downloaded the repository, served the react-search-refiner, and there's no difference on the search box :/ Cheers and  (excited) G

**Comment by FranckyC** [comment] 2018-11-29 13:38
Did you get the latest dev branch? https://github.com/SharePoint/sp-dev-fx-webparts/tree/dev

**Comment by GeoffE1e6** [comment] 2018-11-29 15:01
haha! Silly me - I went for the master not the dev branch! Got it, looking great with the magnifying class working many thanks. Whilst I'm on this topic, would you like to hear of any other suggestions on the user experience? No probs if you dont :) Again, many thanks !

**Comment by FranckyC** [comment] 2018-11-29 15:04
Yes sure! But maybe you could close this one first and open an other issue instead. Thanks!

**Comment by GeoffE1e6** [comment] 2018-11-29 15:19
All sorted, magnifying glass click works a treat!

**Comment by GeoffE1e6** [comment] 2018-11-29 17:30
Opps. Spoke too soon.

On the test site, the 'Search this site' box is hidden on a modern site page above the quick launch bar. Because of that, when dropping the search box web part that will be not be displayed. Am guessing it has a dependancy on the 'Search this site' box... The search this site box needs to be hidden, because the search box is supposed to replace the 'Search this site' box, so, is there anyway of making the magnifying button clickable but without relying on the existence (visibility) of the Search this site box. Hope that makes sense!

If this is visible:
![image](https://user-images.githubusercontent.com/45271893/49239976-09693c80-f3fc-11e8-9cb0-0f59bb74b14d.png)

The search box isn't....

Cheers

G

**Comment by GeoffE1e6** [comment] 2018-11-29 17:31
Sorry! Correction - I meant that if the Search this site is hidden the search box is not displayed.

**Comment by FranckyC** [comment] 2018-11-29 18:34
@GeoffE1e6 not sure to understand. How do you hide the native search box in your site?

**Comment by GeoffE1e6** [comment] 2018-11-29 18:54
Sending this to the domElement.innerHTML
<div id="divhideSearchBox" style="display:none"></div>
and calling this func:

    function hideSearchBox()
    {
            if($('#s4-bodyContainer').length > 0)
                $("#DeltaPlaceHolderSearchArea").hide();
            else
                $("div[class^='searchBox_']").hide();
    }
    function showSearchBox()
    {
        if($("#divHideTitleRow").length == 0 && $("#divHideQuickLaunch").length == 0)
        {
            if($('#s4-bodyContainer').length > 0)      
                $("#DeltaPlaceHolderSearchArea").show();
            else
                $("div[class^='searchBox_']").show();
        }
    }   
    
Essentially, if the search box is not shown, the search box webpart will not be drawn - its totally to do with that magifying glass functionality because that didn't happen before the change am afraid :/

Cheers

G

**Comment by FranckyC** [comment] 2018-11-29 18:59
Haha this is the thing you didn't tell ;). This WP and default search box use the same Office UI Fabric controls and therefore CSS classes...That's why.

In this scenario I can't do anything for you unfortunately since the issue is caused by something you did on the page.

Try to be more specific in your CSS selector to only catch the default search box. Simpply inspect the DOM to see the patern.

**Closed** 2018-11-30 09:17 UTC
