### ISSUE TITLE
React version not working

### ISSUE THREAD

**Issue by Aproximation** [SharePoint/sp-dev-fx-webparts#319] opened 2017-09-28 14:30 UTC
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
Firing "gulp serve" should serve local version of workbench

#### Observed Behavior
400+ errors like:
Error - typescript - node_modules\@types\react\index.d.ts(39,25): error TS1005: ',' expected.
Error - typescript - node_modules\@types\react\index.d.ts(39,27): error TS1005: '>' expected.
Error - typescript - node_modules\@types\react\index.d.ts(3354,0): error TS1128: Declaration or statement expected.
Error - typescript - node_modules\@types\react-dom\index.d.ts(10,9): error TS2305: Module '"<myLocation><myLocation>/node_modules/@types/react/index"' has no exported member 'DOMAttributes'.
Error - typescript - node_modules\@types\react\index.d.ts(17,28): error TS2314: Generic type 'AnimationEvent<T>' requires 1 type argument
(s).
Error - typescript - node_modules\@types\react\index.d.ts(18,28): error TS2314: Generic type 'ClipboardEvent<T>' requires 1 type argument
(s).
Error - typescript - node_modules\@types\react\index.d.ts(19,30): error TS2314: Generic type 'CompositionEvent<T>' requires 1 type argume
nt(s).

[16:09:56] Project test version: 0.0.1
[16:09:56] Build tools version: 2.5.3
[16:09:57] Node version: v6.9.4
[16:09:57] Total duration: 11 s
[16:09:57] Task errors: 448

Installed typescript
+-- @microsoft/sp-build-web@1.1.0
| `-- @microsoft/gulp-core-build-typescript@3.1.1
|   `-- typescript@2.2.2
`-- typescript@2.5.3

I tried both nodeJS v6.9.4 and v6.11.3 - no difference

#### Steps to Reproduce
When creating SPFx project using yeoman pick React version. After it will be created run "gulp serve".

**Comment by waldekmastykarz** [comment] 2017-09-28 17:44
Which version of the SharePoint Framework generator are you using?

**Comment by Aproximation** [comment] 2017-09-28 17:47
Newest one I guess. I've followed [this article ](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment)

**Comment by jbrueggmann** [comment] 2017-10-01 08:30
I experienced the same issue on multiple machines using @microsoft/generator-sharepoint@1.3.1

Switching back to @1.2.0 lets everything run perfectly.

All machines have different node (6 or 7) and typescript versions

**Comment by waldekmastykarz** [comment] 2017-10-01 16:59
I've just created a new project using generator v1.3.1 including a React web part and everything seems to be working just fine. Could you try clearing your local npm cache using `npm cache clean`, deleting the **node_modules** folder in your project and running `npm i` to restore dependencies?

**Comment by waldekmastykarz** [comment] 2017-10-01 17:18
OK, I can reproduce the issue when I create an on-premises React web part using the v1.3.1 generator.

**Comment by waldekmastykarz** [comment] 2017-10-01 17:26
This seems btw. to be a duplicate of https://github.com/SharePoint/sp-dev-docs/issues/892

**Comment by VesaJuvonen** [comment] 2017-10-03 06:36
I'll close this one as a duplicate of [SharePoint/sp-dev-docs#892](https://github.com/SharePoint/sp-dev-docs/issues/892). We are working on a fix.

In general, we would recommend to report all generic issues using the sp-dev-docs issue list at https://github.com/SharePoint/sp-dev-docs/issues/ and use other issue lists for sample issue reporting. This would help in ensuring that we get things processed asap. All issues reported in the sp-dev-docs are being automatically sync'd to our VSTS systems. Thx.

**Closed by VesaJuvonen** 2017-10-03 06:36 UTC
