### ISSUE TITLE
Scripteditor.tsx (not working correctly

### ISSUE THREAD

**Issue by bnagasuri** [SharePoint/sp-dev-fx-webparts#1144] opened 2020-02-19 23:01 UTC
In script.tsx file there are two error super() constructer and on Change unable to call the function for text box filed

**Comment by ValerasNarbutas** [comment] 2020-02-25 06:30
@bnagasuri  maybe you could provide more details on this? code sample?

**Comment by hugoabernier** [comment] 2020-04-04 16:27
@bnagasuri I recently merged a PR that fixes this issue.

If you don't mind, I'll mark it as closed. If you find that the issue isn't resolved, please feel free to re-open it so the community can help finding what else is wrong.

Thanks for reporting the issue in the first place!

**Closed by hugoabernier** 2020-04-04 16:27 UTC
Labels: status:fixed, type:bug
