### ISSUE TITLE
ContentType property not available in Content Query Web Part Results

### ISSUE THREAD

**Issue by ervingayle** [SharePoint/sp-dev-fx-webparts#1053] opened 2019-11-05 16:16 UTC
- [ ] Question
- [X] Bug
- [ ] Enhancement

## Authors
@spplante 

## Expected or Desired Behavior
If a Content Query instance is added to a site page and query configured, you can filter by content query name. If Content Type & Content Type Id are selected as view fields, you will only successfully get Content Type Id. Content Type should be available.

## Observed Behavior

Leveraging {{ContentType.textValue}} doesn't work. {{ContentType.rawValue.ContentType}} does not work either. However, content type id is available

## Steps to Reproduce

Add content query to a page
select site and list criteria
on page 3, select content type and content type id

**Comment by spplante** [comment] 2019-11-05 22:34
@ervingayle the fields and their text/html/raw values are the ones returned by the API, I have no control on why the ContentType wouldn’t be populated.

I will try to take a look on my side to see if I can reproduce but I am pretty sure I won’t be able to help on this one.

**Comment by ervingayle** [comment] 2019-11-05 23:13
@spplante thank you for your reply. I understand that we are limited by what the api provides. My confusion is that we are clearly able to filter by the same content type name and its values as a filter but are unable to reference a content type name value despite the field being listed as available and referencing it in handlebars. Maybe I am thinking about this wrong but wanted to ask as maybe its something that we can find a workaround for.....

**Comment by spplante** [comment] 2019-11-06 14:03
@ervingayle I did reproduce the issue on my side and found the issue. The reason why the API does not return the ContentType is because the content type needs to be "expanded" because it represents another distinct query to get the ContentType information. 

Your problem can be fixed by modifying the following line from the **getListItemsByQuery** method located in the **ListService.ts** file :

Change this :

```typescript
let endpoint = Text.format("{0}/_api/web/lists(guid'{1}')/GetItems?$expand=FieldValuesAsText,FieldValuesAsHtml", webUrl, listId);
```

To this:

```
let endpoint = Text.format("{0}/_api/web/lists(guid'{1}')/GetItems?$expand=FieldValuesAsText,FieldValuesAsHtml,ContentType", webUrl, listId);
```

That way the rawValue should be populated with the following :

![](https://i.ibb.co/HtbJtzY/Screenshot.png)

Rebuild the project with this fix and it should work 👍

**Comment by hugoabernier** [comment] 2020-04-04 17:56
Hey @ervingayle  it looks like @spplante came to the rescue (again!).

I'll mark this issue as closed, but if you need more help resolving this issue, feel free to open a new one.

Thanks @spplante for always taking the time to help!

**Closed by hugoabernier** 2020-04-04 17:56 UTC
Labels: status:answered, type:question
