### ISSUE TITLE
React Content Query WebPart not working with Office 365 Groups based Teamsites?

### ISSUE THREAD

**Issue by schneika** [SharePoint/sp-dev-fx-webparts#292] opened 2017-08-28 07:54 UTC
#### Category
- [X ] Question
- [ ] Bug
- [ ] Enhancement

#### Observed Behavior
I am not able to retrieve any Office 365 Groups based Teamsite:
An error occured while loading fields : The previously configured web url '/sites/TeamSiteOfGroup' is not found anymore. Either leave the WebPart properties as is or select another web url.

**Comment by spplante** [comment] 2017-08-28 12:21
Hi Scheneika, this error message is usually displayed when a WebPart has been previously configured on a particular web, on which the current user doesn't have access to. The WebPart does not run with elevated privileges, which means it uses the current user's permissions so if the current user doesn't have access to the said web, even if it exist, he won't be able to configure the WebPart on it.

Example : UserA has access to TestWeb, configures the WebPart on that same TestWeb, and publishes the page. Then, UserB, which does not have access to TestWeb, edits the page and edits the WebPart, then this message should be displayed, because the UserB does not have access to the TestWeb site which was previously configured by UserA, so the WebPart is unable to load the fields out of the web.

If this is your issue, this is by design as the WebPart is running under the current user's context. This is unfortunately a limitation as you have to make sure the WebPart is configured with a user that has sufficient permissions.

If your user does have all the required permissions and you still see this error, then it might be something that has to do with Group team sites, I will take a look at it if it's the case :)

**Comment by spplante** [comment] 2017-08-31 23:32
Hi @schneika,

After investiguating a similar issue ([Issue 288](https://github.com/SharePoint/sp-dev-fx-webparts/issues/288)), I found a minor mistake that turned out to have a pretty big impact on the WebPart : The search query responsible for filling the **Web Url** dropdown within the WebPart's toolpane had no **rowLimit** parameter specified, causing the query to return a maximum of **10** results since **10** is the default **rowLimit** value when not specified.

I updated the code by adding a **rowLimit** of 500 results in order to really get all sites on which the current user has access. This should work much better now :)

The pull request #296 has been submitted, you can either access the updated code or .sppkg directly from [my fork](https://github.com/spplante/sp-dev-fx-webparts/tree/dev/samples/react-content-query-webpart), or wait for the pull request #296 to be merged in here to the master branch.

@VesaJuvonen You can close this issue as soon as #296 is merged :)

**Comment by VesaJuvonen** [comment] 2017-09-01 11:02
Closing since PR has been merged. Thx everyone!

**Closed by VesaJuvonen** 2017-09-01 11:02 UTC

**Comment by spplante** [comment] 2017-09-02 04:48
FYI @schneika, I just submitted my pull request #299 whichnow allows the user to select a site collection before selecting the actual subsite. This narrows down by a lot the amount of results that are displayed in each dropdown. 

I also modified the search request used for filling both properties by using a recursive promise approach, which basically loads urls in batch of 500 results (maximum allowed in one call by the REST API) until everything is loaded.

This removes the 500 items rowLimit bottleneck and allows the WebPart to search for unlimited results and avoid any kind of missing sites behavior :)
